### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Maxisoft5** [Maxisoft5/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Maxisoft4** [comment]
45th President of the United States of America. The beauty of me is that I'm very rich. You know, it really doesn't matter what the media write, as long as you've got a young and beautiful piece of ass. Despite the constant negative press covfefe. Anyway, shut up, build me a website. We will build a great website ― and nobody builds websites better than me, believe me ― and I'll build them very inexpensively.
