### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Maxisoft5** [Maxisoft5/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Maxisoft4** [comment]
https://twitter.com/realdonaldtrump
https://www.instagram.com/realdonaldtrump/?hl=ru
https://ru-ru.facebook.com/DonaldTrump/
https://en.wikipedia.org/wiki/Donald_Trump
https://www.whitehouse.gov/people/donald-j-trump/
https://www.donaldjtrump.com/contact/
Phone number: 202-456-1111
Address: The White House
1600 Pennsylvania Avenue NW
Washington, DC 20500

**Comment by Maxisoft4** [comment]
<h1 class="name">Donald John Trump</h1>
                    <div class = "job">President of the United States</div>
                    <ul class = "contacts">
                      <li>
                        <a href="https://twitter.com/realdonaldtrump" rel ="author" class="twitter"> 
                          <img src="https://img.icons8.com/nolan/64/twitter.png" width="20px" height="20px" class = "icon"/>
                           <span>Donald's Twitter</span>
                        </a>
                       </li>
                      <li>
                        <a href="https://www.instagram.com/realdonaldtrump/?hl=ru" rel ="author" class="instagram">
                          <img src="./assets/images/instagram-icon.svg" width="20px" height="20px" class ="icon"/>
                          <span>Donald's Instagram</span>
                        </li>
                      </a>
                      <li>
                        <a href="https://ru-ru.facebook.com/DonaldTrump/" rel ="author" class="facebook">
                        <img src="./assets/images/facebook.svg" width="20px" height="20px" class = "icon"/>
                        <span>Donald's Facebook</span>
                      </a>
                      </li>
                      <li>
                        <a href="https://en.wikipedia.org/wiki/Donald_Trump" rel ="author" class="wiki">
                        <img src="./assets/images/wiki.png" width="20px" height="20px" class = "icon"/>
                        <span>Donald's Wiki</span>
                      </a>
                      </li>
                      <li>
                        <a href="https://www.whitehouse.gov/people/donald-j-trump/" rel ="author" class="whitehouse">
                        <img src="./assets/images/white-house.svg" width="20px" height="20px" class = "icon"/>
                        <span> White House profile</span>
                      </a>
                      </li>
                      <li>
                        <a href="tel:+1-202-456-111" rel ="author" class="phone">
                        <img src="https://img.icons8.com/metro/26/000000/phone.png" width="20px" height="20px" class = "icon"/>
                        <span>202-456-111</span>
                      </a>
                      </li>
                      <ul>
