### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Maxisoft5** [Maxisoft5/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Maxisoft4** [comment]
- June 14, 1946 Donald John Trump is born in New York City
- 1968 Trump graduates from University of Pennsylvania's Wharton School of Finance
- 1971 He took charge of his family's real-estate business in 1971
- 1980 He opened the Grand Hyatt New York, which made him the city's best-known developer. 
- 1983 Trump Tower open in Manhattan
- 2004 The Apprentice television series debuts
- July 2016 The Republicans officially name Trump as their presidential nominee
- November 2016 Trump is elected president
