### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Maxisoft5** [Maxisoft5/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Maxisoft4** [comment]
**LANGUAGES** 

English, Czech, Russian, French 

**SKILSS**

Confidence Authoratitive Dauntless Deal-maker Prudent With Resources Self-interest First Clear Priorities Financial Understanding

**CHARACTER**

His personality is captured by his reputation, which is the sum of his behavior, and organized by a standard set of themes as follows. 

**LIKES**

Mr. Trump seems competitive, wants to win, and wants to be in charge

**DISLIKES**

Highly Bold Highly Mischievous Highly Colorful Low on Diligence Low on Dutifulness
